"""Compile the offline UI dictionary for Lua and the Windows HUD."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
data = json.loads((ROOT / 'localization/ui.json').read_text(encoding='utf-8'))
languages = data['languages']
rows = data['strings']
assert len(languages) == 10 and languages[0] == 'en'
for key, values in rows.items():
    assert len(values) == 9 and all(isinstance(v, str) and v for v in values), key
    import re
    tokens = sorted(re.findall(r'\{\d+\}', key))
    assert all(sorted(re.findall(r'\{\d+\}', v)) == tokens for v in values), key

def quote(value):
    return json.dumps(value, ensure_ascii=False)

lua = ['-- Generated by scripts/Build-UiCatalog.py from localization/ui.json.', 'return {rows={']
cs = ['// Generated by scripts/Build-UiCatalog.py from localization/ui.json.',
      'using System.Collections.Generic;', 'public static class UiStrings {',
      ' public static readonly Dictionary<string,string[]> Rows = new Dictionary<string,string[]> {']
for key, values in rows.items():
    lua.append(' [' + quote(key) + ']={' + ','.join(quote(v) for v in values) + '},')
    cs.append('  {' + quote(key) + ',new[]{' + ','.join(quote(v) for v in values) + '}},')
lua.append('},help={')
for key, value in data.get('settingHelp', {}).items():
    lua.append(' [' + quote(key) + ']=' + quote(value) + ',')
lua.append('}}')
cs += [' };', '}']
(ROOT / 'mod/Scripts/ui_translations.lua').write_text('\n'.join(lua) + '\n', encoding='utf-8')
(ROOT / 'bridge/UiStrings.cs').write_text('\n'.join(cs) + '\n', encoding='utf-8')
print(f'Compiled {len(rows)} strings in {len(languages)} languages.')
